// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'core/config/flavor_config.dart';

/// Flavor-aware [FirebaseOptions] factory for different environments.
///
/// Use [FirebaseOptionsFactory.getOptions] to get Firebase configuration
/// for a specific flavor and platform.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// import 'core/config/flavor_config.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: FirebaseOptionsFactory.getOptions(FlavorConfig.instance.flavor),
/// );
/// ```
class FirebaseOptionsFactory {
  /// Get Firebase options for the given flavor and current platform.
  ///
  /// Throws [UnsupportedError] if the platform is not configured.
  static FirebaseOptions getOptions(Flavor flavor) {
    if (kIsWeb) {
      throw UnsupportedError(
        'FirebaseOptions have not been configured for web',
      );
    }

    switch (flavor) {
      case Flavor.dev:
        return _getDevOptions();
      case Flavor.prod:
        return _getProdOptions();
    }
  }

  /// Backward compatibility: get options for current platform using prod flavor.
  ///
  /// @deprecated Use [getOptions] with explicit flavor instead.
  @Deprecated('Use getOptions(FlavorConfig.instance.flavor) instead')
  static FirebaseOptions get currentPlatform => getOptions(Flavor.prod);

  static FirebaseOptions _getDevOptions() {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _androidDev;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS dev Firebase configuration is not yet set up. '
          'Please configure the iOS dev app in Firebase Console and '
          'run `flutterfire configure` to generate the proper options.',
        );
      default:
        throw UnsupportedError(
          'FirebaseOptions are not configured for $defaultTargetPlatform in dev flavor',
        );
    }
  }

  static FirebaseOptions _getProdOptions() {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _androidProd;
      case TargetPlatform.iOS:
        return _iosProd;
      default:
        throw UnsupportedError(
          'FirebaseOptions are not configured for $defaultTargetPlatform in prod flavor',
        );
    }
  }

  // Production Firebase configurations
  static const FirebaseOptions _androidProd = FirebaseOptions(
    apiKey: 'AIzaSyCM70DyzvDa9QqjJQ0q_aZoHaxJjDGHZK8',
    appId: '1:836631105553:android:add75ab3601be0066ca1b0',
    messagingSenderId: '836631105553',
    projectId: 'ease-queue',
    storageBucket: 'ease-queue.firebasestorage.app',
  );

  static const FirebaseOptions _iosProd = FirebaseOptions(
    apiKey: 'AIzaSyBFqoyb-phsY_tlc5FZctp4yhuziH8OrqA',
    appId: '1:836631105553:ios:a5158afe99340b356ca1b0',
    messagingSenderId: '836631105553',
    projectId: 'ease-queue',
    storageBucket: 'ease-queue.firebasestorage.app',
    iosBundleId: 'com.example.queueEase',
  );

  // Development Firebase configurations
  static const FirebaseOptions _androidDev = FirebaseOptions(
    apiKey: 'AIzaSyCTL05OIbysTMI9CcXR5nIp1h7giGevX9E',
    appId: '1:811891961988:android:f732635ea023c08a9692d1',
    messagingSenderId: '811891961988',
    projectId: 'ease-queue-dev',
    storageBucket: 'ease-queue-dev.firebasestorage.app',
  );
}

/// Legacy alias for backward compatibility
@Deprecated('Use FirebaseOptionsFactory instead')
typedef DefaultFirebaseOptions = FirebaseOptionsFactory;
